-- ============================================================
-- EventHub - Clase 06
-- V1__init_core.sql
-- Primera migración del núcleo de la base de datos
-- ============================================================


-- ============================================================
-- 1. USUARIO
-- ============================================================

CREATE TABLE usuario (
                         usuario_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                         nombre VARCHAR(100) NOT NULL,
                         apellido VARCHAR(100) NOT NULL,
                         correo VARCHAR(254) NOT NULL,
                         rol VARCHAR(50) NOT NULL,
                         created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                         CONSTRAINT pk_usuario
                             PRIMARY KEY (usuario_id)
);


-- ============================================================
-- 2. PARTICIPANTE
-- ============================================================

CREATE TABLE participante (
                              participante_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                              nombre VARCHAR(100) NOT NULL,
                              apellido VARCHAR(100) NOT NULL,
                              correo VARCHAR(254) NOT NULL,
                              created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                              updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                              CONSTRAINT pk_participante
                                  PRIMARY KEY (participante_id)
);


-- ============================================================
-- 3. EVENTO
-- ============================================================

CREATE TABLE evento (
                        evento_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                        nombre VARCHAR(150) NOT NULL,
                        descripcion TEXT,
                        responsable VARCHAR(150) NOT NULL,
                        modalidad VARCHAR(50) NOT NULL,
                        fecha_inicio TIMESTAMPTZ NOT NULL,
                        fecha_fin TIMESTAMPTZ NOT NULL,
                        capacidad INTEGER NOT NULL,
                        estado VARCHAR(20) NOT NULL,
                        usuario_id BIGINT NOT NULL,
                        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                        CONSTRAINT pk_evento
                            PRIMARY KEY (evento_id),

                        CONSTRAINT fk_evento_usuario
                            FOREIGN KEY (usuario_id)
                                REFERENCES usuario(usuario_id),

                        CONSTRAINT ck_evento_capacidad
                            CHECK (capacidad > 0),

                        CONSTRAINT ck_evento_estado
                            CHECK (
                                estado IN (
                                           'BORRADOR',
                                           'PUBLICADO',
                                           'EN_CURSO',
                                           'FINALIZADO',
                                           'CANCELADO'
                                    )
                                ),

                        CONSTRAINT ck_evento_fechas
                            CHECK (fecha_fin >= fecha_inicio)
);


-- ============================================================
-- 4. SESION_EVENTO
-- ============================================================

CREATE TABLE sesion_evento (
                               sesion_evento_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                               evento_id BIGINT NOT NULL,
                               fecha_inicio TIMESTAMPTZ NOT NULL,
                               fecha_fin TIMESTAMPTZ NOT NULL,
                               created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                               CONSTRAINT pk_sesion_evento
                                   PRIMARY KEY (sesion_evento_id),

                               CONSTRAINT fk_sesion_evento_evento
                                   FOREIGN KEY (evento_id)
                                       REFERENCES evento(evento_id),

                               CONSTRAINT ck_sesion_evento_fechas
                                   CHECK (fecha_fin > fecha_inicio)
);


-- ============================================================
-- 5. INSCRIPCION
-- ============================================================

CREATE TABLE inscripcion (
                             inscripcion_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                             participante_id BIGINT NOT NULL,
                             evento_id BIGINT NOT NULL,
                             fecha_inscripcion TIMESTAMPTZ NOT NULL,
                             estado VARCHAR(30) NOT NULL,
                             usuario_id BIGINT NOT NULL,
                             created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                             CONSTRAINT pk_inscripcion
                                 PRIMARY KEY (inscripcion_id),

                             CONSTRAINT fk_inscripcion_participante
                                 FOREIGN KEY (participante_id)
                                     REFERENCES participante(participante_id),

                             CONSTRAINT fk_inscripcion_evento
                                 FOREIGN KEY (evento_id)
                                     REFERENCES evento(evento_id),

                             CONSTRAINT fk_inscripcion_usuario
                                 FOREIGN KEY (usuario_id)
                                     REFERENCES usuario(usuario_id),

                             CONSTRAINT uq_inscripcion_participante_evento
                                 UNIQUE (participante_id, evento_id),

                             CONSTRAINT ck_inscripcion_estado
                                 CHECK (
                                     estado IN (
                                                'PENDIENTE',
                                                'CONFIRMADA',
                                                'CANCELADA'
                                         )
                                     )
);